[build]
  command = "npm run build"
  publish = "out"

[[redirects]]
  from = "/api/*"
  to = "https://secux-dapp-demo.netlify.app/:splat"
  status = 200
  force = true
[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
      Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
