"use client";

import Head from "next/head";
import Image from "next/image";
import { Account } from "../../components/Account";

export default function VerifierPage() {
  return (
    <div>
      <main>
        <div className="px-5">
          <p></p>
          <span className="block text-2xl font-bold">
            Battery-Free Smart Tags - Professor Patrick Mercier and his team at the University of California, San Diego,
            have developed an RFID smart tag that uses the signals generated by a smartphone to both read and power it
          </span>
          <p></p>
          <span className="block text-2xl font-bold">to contact issuers, delegate Signer</span>
          <p></p>
          <span className="block text-2xl font-bold">Showcases to blockchain developer communities</span>
          <p></p>
          <span className="block text-2xl font-bold">Machine Learning Verifiable Claims Verification</span>
          <hr />
        </div>
      </main>
      <div className="flex justify-center items-center gap-12 flex-col sm:flex-row">
        <Image src="/cfa-2.png" alt="Example Image" width={800} height={600} />
        <Image src="/cfa-1.png" alt="Example Image" width={800} height={600} />
      </div>
    </div>
  );
}
